version: '3.8'
services:
  blog-api:
    image: goon/blog-api:${TAG:-latest}
    build:
      context: ./services/blog
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    depends_on:
      - blogdata
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:rG5uMcth6cEQY5OZ5MZ9TfmweANPAFswaQs1+wFoRmw=
      DB_CONNECTION: mysql
      DB_HOST: blogdata
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: redis
    ports:
      - "8001:8000"

  blogdata:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/blog/mysql:/var/lib/mysql

#  redis:
#    image: redis:6.2-alpine
#    restart: unless-stopped
#    volumes:
#      - ./api/storage/redis:/data
#    ports:
#      - 63790:6379
