version: '3.8'
services:
  gateway:
    image: goon/gateway:${TAG:-latest}
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - identity-api
      - blog-api
      - learn-api

  identity-api:
    image: goon/identity-api:${TAG:-latest}
    build:
      context: ./services/identity
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_NAME: Goon
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:rG5uMcth6cEQY5OZ5MZ9TfmweANPAFswaQs1+wFoRmw=
      DB_CONNECTION: mysql
      DB_HOST: blog-db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: redis

  learn-api:
    image: kiwix/kiwix-serve:${TAG:-latest}
    restart: unless-stopped
    command: "*.zim"
    volumes:
      - ./services/learn:/data

  blog-api:
    image: goon/blog-api:${TAG:-latest}
    build:
      context: ./services/blog
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - blog-db
    environment:
      APP_NAME: Goon
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:rG5uMcth6cEQY5OZ5MZ9TfmweANPAFswaQs1+wFoRmw=
      DB_CONNECTION: mysql
      DB_HOST: blog-db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      QUEUE_CONNECTION: redis

  blog-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/blog/mysql:/var/lib/mysql

#  redis:
#    image: redis:6.2-alpine
#    restart: unless-stopped
#    volumes:
#      - ./api/storage/redis:/data
#    ports:
#      - 63790:6379
